package org.datapress.jdbc;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import org.apache.arrow.memory.BufferAllocator;
import org.datapress.jdbc.internal.arrow.ArrowResultIterator;
import org.datapress.jdbc.internal.http.SqlErrors;

/**
 * A read-only, forward-only {@link Statement}. {@code executeQuery} POSTs to {@code /api/v1/sql}
 * requesting an Arrow IPC stream and wraps the response in a streaming {@link DataPressResultSet}.
 * Every update-shaped operation raises {@code 0A000}.
 */
class DataPressStatement implements Statement {

  private final DataPressConnection connection;
  private final BufferAllocator allocator; // child of the connection root; owned by this statement

  private int maxRows;
  private int fetchSize;
  private int queryTimeout;
  private boolean poolable;
  private boolean closeOnCompletion;
  private boolean closed;
  private DataPressResultSet currentResultSet;

  DataPressStatement(DataPressConnection connection, BufferAllocator allocator) {
    this.connection = connection;
    this.allocator = allocator;
  }

  final void checkOpen() throws SQLException {
    if (closed) {
      throw SqlErrors.closed("Statement");
    }
  }

  /** Effective {@code max_rows}: the per-statement cap, else the connection default, else 0. */
  private int effectiveMaxRows() {
    if (maxRows > 0) {
      return maxRows;
    }
    return connection.config().maxRows();
  }

  /** Runs an already-rendered SQL string and installs the streaming result set. */
  final DataPressResultSet runQuery(String sql) throws SQLException {
    checkOpen();
    closeCurrentResultSet();
    InputStream stream = connection.http().executeSql(sql, effectiveMaxRows());
    BufferAllocator resultAllocator = allocator.newChildAllocator("resultset", 0, Long.MAX_VALUE);
    ArrowResultIterator iterator = new ArrowResultIterator(stream, resultAllocator);
    try {
      DataPressResultSet resultSet = new DataPressResultSet(this, iterator, resultAllocator);
      currentResultSet = resultSet;
      return resultSet;
    } catch (SQLException | RuntimeException e) {
      closeQuietly(iterator);
      resultAllocator.close();
      throw e;
    }
  }

  private static void closeQuietly(ArrowResultIterator iterator) {
    try {
      iterator.close();
    } catch (Exception ignored) {
      // best effort
    }
  }

  private void closeCurrentResultSet() {
    if (currentResultSet != null) {
      currentResultSet.close();
      currentResultSet = null;
    }
  }

  /** Callback from {@link DataPressResultSet#close()} so the statement can drop its reference. */
  void resultSetClosed(DataPressResultSet resultSet) {
    if (resultSet == currentResultSet) {
      currentResultSet = null;
    }
    if (closeOnCompletion) {
      close();
    }
  }

  // --- Execution ------------------------------------------------------------------------------

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    return runQuery(sql);
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    runQuery(sql);
    return true; // the driver always yields a result set (read-only)
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    return execute(sql);
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    return execute(sql);
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    return execute(sql);
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    checkOpen();
    throw SqlErrors.unsupported("executeUpdate (the driver is read-only)");
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public long executeLargeUpdate(String sql) throws SQLException {
    checkOpen();
    throw SqlErrors.unsupported("executeLargeUpdate (the driver is read-only)");
  }

  @Override
  public ResultSet getResultSet() throws SQLException {
    checkOpen();
    return currentResultSet;
  }

  @Override
  public int getUpdateCount() throws SQLException {
    checkOpen();
    return -1; // never an update
  }

  @Override
  public long getLargeUpdateCount() throws SQLException {
    checkOpen();
    return -1L;
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    checkOpen();
    closeCurrentResultSet();
    return false;
  }

  @Override
  public boolean getMoreResults(int current) throws SQLException {
    checkOpen();
    if (current != KEEP_CURRENT_RESULT) {
      closeCurrentResultSet();
    }
    return false;
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    checkOpen();
    throw SqlErrors.unsupported("Auto-generated keys");
  }

  // --- Batches (unsupported, read-only) -------------------------------------------------------

  @Override
  public void addBatch(String sql) throws SQLException {
    throw SqlErrors.unsupported("Batch updates");
  }

  @Override
  public void clearBatch() throws SQLException {
    checkOpen();
    // No batch is ever accumulated; nothing to clear.
  }

  @Override
  public int[] executeBatch() throws SQLException {
    throw SqlErrors.unsupported("Batch updates");
  }

  // --- Limits / hints -------------------------------------------------------------------------

  @Override
  public int getMaxFieldSize() throws SQLException {
    checkOpen();
    return 0;
  }

  @Override
  public void setMaxFieldSize(int max) throws SQLException {
    checkOpen();
    // Unbounded field size; hint ignored.
  }

  @Override
  public int getMaxRows() throws SQLException {
    checkOpen();
    return maxRows;
  }

  @Override
  public void setMaxRows(int max) throws SQLException {
    checkOpen();
    if (max < 0) {
      throw new SQLException("maxRows must not be negative: " + max);
    }
    this.maxRows = max;
  }

  @Override
  public long getLargeMaxRows() throws SQLException {
    checkOpen();
    return maxRows;
  }

  @Override
  public void setLargeMaxRows(long max) throws SQLException {
    checkOpen();
    if (max < 0) {
      throw new SQLException("maxRows must not be negative: " + max);
    }
    this.maxRows = (int) Math.min(max, Integer.MAX_VALUE);
  }

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException {
    checkOpen();
    // The driver does not translate JDBC escape syntax; ignored.
  }

  @Override
  public int getQueryTimeout() throws SQLException {
    checkOpen();
    return queryTimeout;
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    checkOpen();
    if (seconds < 0) {
      throw new SQLException("queryTimeout must not be negative: " + seconds);
    }
    this.queryTimeout = seconds;
  }

  @Override
  public void cancel() throws SQLException {
    // Streaming HTTP requests cannot be cancelled mid-flight; treated as a no-op.
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    checkOpen();
    return null;
  }

  @Override
  public void clearWarnings() throws SQLException {
    checkOpen();
  }

  @Override
  public void setCursorName(String name) throws SQLException {
    throw SqlErrors.unsupported("Named cursors");
  }

  @Override
  public int getFetchDirection() throws SQLException {
    checkOpen();
    return ResultSet.FETCH_FORWARD;
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    checkOpen();
    if (direction != ResultSet.FETCH_FORWARD) {
      throw SqlErrors.unsupported("Fetch direction other than FETCH_FORWARD");
    }
  }

  @Override
  public int getFetchSize() throws SQLException {
    checkOpen();
    return fetchSize;
  }

  @Override
  public void setFetchSize(int rows) throws SQLException {
    checkOpen();
    if (rows < 0) {
      throw new SQLException("fetchSize must not be negative: " + rows);
    }
    this.fetchSize = rows;
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    checkOpen();
    return ResultSet.CONCUR_READ_ONLY;
  }

  @Override
  public int getResultSetType() throws SQLException {
    checkOpen();
    return ResultSet.TYPE_FORWARD_ONLY;
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    checkOpen();
    return ResultSet.CLOSE_CURSORS_AT_COMMIT;
  }

  @Override
  public Connection getConnection() throws SQLException {
    checkOpen();
    return connection;
  }

  @Override
  public boolean isPoolable() throws SQLException {
    checkOpen();
    return poolable;
  }

  @Override
  public void setPoolable(boolean poolable) throws SQLException {
    checkOpen();
    this.poolable = poolable;
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    checkOpen();
    this.closeOnCompletion = true;
  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    checkOpen();
    return closeOnCompletion;
  }

  // --- Lifecycle ------------------------------------------------------------------------------

  @Override
  public void close() {
    if (closed) {
      return;
    }
    closed = true;
    closeCurrentResultSet();
    allocator.close();
    connection.statementClosed(this);
  }

  @Override
  public boolean isClosed() {
    return closed;
  }

  // --- Wrapper --------------------------------------------------------------------------------

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isInstance(this)) {
      return iface.cast(this);
    }
    throw new SQLException("Not a wrapper for " + iface.getName());
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) {
    return iface.isInstance(this);
  }
}
